// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $interview from "./routes/interview.tsx";
import * as $network from "./routes/network.tsx";
import * as $resume from "./routes/resume.tsx";
import * as $worldMap from "./routes/worldMap.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $MapIsland from "./islands/MapIsland.tsx";
import * as $Nav from "./islands/Nav.tsx";
import * as $P5Canvas from "./islands/P5Canvas.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/api/joke.ts": $api_joke,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/interview.tsx": $interview,
    "./routes/network.tsx": $network,
    "./routes/resume.tsx": $resume,
    "./routes/worldMap.tsx": $worldMap,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
    "./islands/MapIsland.tsx": $MapIsland,
    "./islands/Nav.tsx": $Nav,
    "./islands/P5Canvas.tsx": $P5Canvas,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
